#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/load_site_config.sh"

OUTPUT_FILE="$ROOT_DIR/config/site.env.local"
EXPLICIT_API_BASE=0
unset WAFERDB_API_BASE

usage() {
    cat <<'EOF'
Usage:
  bash scripts/restore_local_site_env.sh [options]

Options:
  --scheme VALUE
  --host VALUE
  --port VALUE
  --context-path VALUE
  --db-path VALUE
  --darkfield-root VALUE
  --allowed-origin VALUE
  --dist-label VALUE
  --api-base VALUE
  --output FILE
  --help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --scheme)
            WAFERDB_SCHEME="$2"
            shift 2
            ;;
        --host)
            WAFERDB_HOST="$2"
            shift 2
            ;;
        --port)
            WAFERDB_PORT="$2"
            shift 2
            ;;
        --context-path)
            WAFERDB_CONTEXT_PATH="$2"
            shift 2
            ;;
        --db-path)
            WAFERDB_DB_PATH="$2"
            shift 2
            ;;
        --darkfield-root)
            WAFERDB_DARKFIELD_ROOT="$2"
            shift 2
            ;;
        --allowed-origin)
            WAFERDB_ALLOWED_ORIGIN="$2"
            shift 2
            ;;
        --dist-label)
            WAFERDB_DIST_LABEL="$2"
            shift 2
            ;;
        --api-base)
            WAFERDB_API_BASE="$2"
            EXPLICIT_API_BASE=1
            shift 2
            ;;
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

mkdir -p "$(dirname "$OUTPUT_FILE")"

write_var() {
    printf '%s=%q\n' "$1" "$2" >> "$OUTPUT_FILE"
}

: > "$OUTPUT_FILE"
{
    echo "# Generated by scripts/restore_local_site_env.sh"
    echo "# This file is intentionally gitignored."
} >> "$OUTPUT_FILE"
write_var "WAFERDB_SCHEME" "$WAFERDB_SCHEME"
write_var "WAFERDB_HOST" "$WAFERDB_HOST"
write_var "WAFERDB_PORT" "$WAFERDB_PORT"
write_var "WAFERDB_CONTEXT_PATH" "$WAFERDB_CONTEXT_PATH"
write_var "WAFERDB_DB_PATH" "$WAFERDB_DB_PATH"
write_var "WAFERDB_DARKFIELD_ROOT" "$WAFERDB_DARKFIELD_ROOT"
write_var "WAFERDB_ALLOWED_ORIGIN" "$WAFERDB_ALLOWED_ORIGIN"
write_var "WAFERDB_DIST_LABEL" "$WAFERDB_DIST_LABEL"
if [[ "$EXPLICIT_API_BASE" -eq 1 ]]; then
    write_var "WAFERDB_API_BASE" "$WAFERDB_API_BASE"
fi

echo "Wrote $OUTPUT_FILE"
